### PR TITLE
Import website repo code

### PR DESCRIPTION
**Pull request by AnupKumarPanwar**
The PR replaces the existing website code with the one present in https://github.com/TheAlgorithms/website.
After this PR is merged the other repo can be archived.

Existing site: https://thealgorithms.github.io/
How new site would look: https://thealgorithms.github.io/website

The final URL stays https://thealgorithms.github.io/

### CODE REVIEW

**Comment by cclauss** [comment]
rebase perhaps?

**Comment by AnshulMalik** [comment]
@cclauss These are commits from another repository. I think this is how it should look.

**Review by AnshulMalik — APPROVED** [review]

**Review by nikhilkala — APPROVED** [review]
This website look is more concise and appealing.

**Comment by cclauss** [comment]
A public repo with no LICENSE?

**Comment by itsvinayak** [comment]
@AnupKumarPanwar we should rebase and merge it

**Comment by mrmaxguns** [comment]
I'll close this PR since TheAlgorithms has a new website.

**Pull request closed without merging**
