### PR TITLE
[improvement] C,cpp links to doc sites instead

### LINKED ISSUE #14: Links to raw repo or documentation sites?
There has been a development on creating auto-generated interactive documentations for some repos-
* https://thealgorithms.github.io/C
* https://thealgorithms.github.io/C-Plus-Plus
and has raised some questions on the direction to proceed.

I see softwares and software libraries provide initial links to their documentation sites and within there, links to their code repos. As an educational platform, wouldn't the docs be more beneficial to the readers who can then navigate to the repo and the respective codes?

### Questions
1. What value do users/readers get from links to raw repo?
2. Is there a value to generate auto-docs for each repo in a similar fashion to their respective `gh-pages` branches?
3. Should the main website provide links to these docs instead? 
4. This would, however require the contributors to properly document their contributions and would intern improve the quality of code being accepted to the repos. Is the reviewers' time consumed outweighed by the benefits?

(Did I miss anything else?)

### PR DESCRIPTION
**Pull request by kvedala**
C/C++ links to doc sites instead instead of GitHub Repo sites

### CODE REVIEW

**Comment by cclauss** [comment]
I am not a fan of this change.  Our primary deliverable is our algorithms, not our docs.

**Comment by mrmaxguns** [comment]
I think this would be nice, however, that would mean that the links aren't standardized. Some will point to the repos while others will point to their websites.

**Comment by kvedala** [comment]
> I am not a fan of this change. Our primary deliverable is our algorithms, not our docs.

Isn't it to provide with educative and learning resources? How does a raw repo that does not have a navigation better than a well-formatted website that does also provide access the toe same raw codes?

**Comment by kvedala** [comment]
> I think this would be nice, however, that would mean that the links aren't standardized. Some will point to the repos while others will point to their websites.

Agreed. This would mean that the other repositories also generate a formatted output. I think Python repo is already good to generate Sphinx docs or read-the-docs kind of sites.

**Comment by mrmaxguns** [comment]
> Agreed. This would mean that the other repositories also generate a formatted output. I think Python repo is already good to generate Sphinx docs or read-the-docs kind of sites.

Definitely. The python repository is extremely large and docs aren't a requirement. It would already require extensive documentation.

I think we should standardize either the sites or repositories, not both as it would lead to a mess.

**Comment by kvedala** [comment]
> > Agreed. This would mean that the other repositories also generate a formatted output. I think Python repo is already good to generate Sphinx docs or read-the-docs kind of sites.
> 
> Definitely. The python repository is extremely large and docs aren't a requirement. It would already require extensive documentation.
> 
> I think we should standardize either the sites or repositories, not both as it would lead to a mess.

Agreed

**Comment by mrmaxguns** [comment]
I'll close this PR since TheAlgorithms has a new website.

**Pull request closed without merging**
