### PR TITLE
improve style

### PR DESCRIPTION
**Pull request by itsvinayak**

### CODE REVIEW

**Comment by mrmaxguns** [comment]
@itsvinayak Great! Just one problem. You removed the section about gitter, but didn't remove the link to the section in the navbar. It should probably either be removed, or be linked with the gitter page.

**Comment by itsvinayak** [comment]
@mrmaxguns it's not completed yet, more changes to come
there are several tasks to be  completed like cleaning up the codebase and removing bootstrap if we can(because of CDN's  they increase the overall load time), organize all SVG's 

that's why I was asking what wrong with the current homepage, any idea

**Comment by cclauss** [comment]
@mrmaxguns Please submit a PR to restore the functionality that was removed.

**Comment by mrmaxguns** [comment]
@itsvinayak okay, do as you see fit

**Pull request merged**
